### PR TITLE
Add note about zero xmag/ymag

### PR DESCRIPTION
**Pull request by lexaknyazev**
We can't disallow such case with schema, but it's worth noting.

### CODE REVIEW

**Comment by bghgary** [comment]
What about the other cases that result in a division by zero (e.g. n == f or y == 0)? I'm wondering if this note is necessary.

**Comment by lexaknyazev** [comment]
Corner cases for perspective camera are covered by schema.

**Comment by bghgary** [comment]
I see y == 0 is restricted by schema, but where is n == f restricted?

**Comment by bghgary** [comment]
Oh, never mind. I see it in the description.

**Comment by bghgary** [comment]
To be consistent, perhaps, the note should go in the schema description?

**Comment by pjcozzi** [comment]
@lexaknyazev do you have a reference to the discussion when we decided to allow this to be undefined instead of just not allow these cases?

**Comment by lexaknyazev** [comment]
@pjcozzi 
> we decided to allow this to be undefined 

I think that such corner case was overlooked. Anyway, it's difficult (not impossible, though) to disallow it with JSON-Schema. Moreover, I think that we can't change the schema anymore.

@bghgary 
> To be consistent, perhaps, the note should go in the schema description?

:+1:

**Comment by lexaknyazev** [comment]
Moved note to schema description.
@pjcozzi Please merge if it's fine.

**Comment by pjcozzi** [comment]
I'm still a bit lost here - was there a discussion about this that we are able to reference here where we decided that undefined behavior was preferred compared to disallowing the divide by zero cases?

**Comment by lexaknyazev** [comment]
> was there a discussion about this

I don't think so.

**Comment by pjcozzi** [comment]
OK, why do we think undefined behavior is better than disallowing these cases?

**Comment by lexaknyazev** [comment]
> OK, why do we think undefined behavior is better than disallowing these cases?

Do you think it's possible to make such change after spec release?

**Comment by pjcozzi** [comment]
I think we could put this as a spec bug fix.  Let's confirm tomorrow.

**Comment by lexaknyazev** [comment]
@pjcozzi 
Please check updated description and merge if it's fine.

**Comment by pjcozzi** [comment]
Should this be non-zero or `> 0`?

**Comment by pjcozzi** [comment]
Also, shouldn't the .md also be updated?

**Comment by lexaknyazev** [comment]
Prop. reference will be updated on the next regen (it should happen soon).

**Comment by lexaknyazev** [comment]
> Should this be non-zero or `> 0`?

Negative values could be used to flip final image. I'm not sure about disallowing such case.

**Comment by pjcozzi** [comment]
Gotcha!

**Pull request merged**
