### PR TITLE
Add MSFT vendor extensions 

### PR DESCRIPTION
**Pull request by sbtron**
Merging these Microsoft specific extensions back into master so that they are more discoverable. 

There are some ongoing discussions for others adopting some of these like the LOD extension. If there is interest in that, a separate multi-vendor extension can be added. Wanted to get these is in so that there is good documentation/snapshot of what we are currently doing.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@sbtron are these already pretty well vetted and implemented?  Or do you want anyone to look at these before merging?  As a vendor extension, it is totally up to you.

**Comment by sbtron** [comment]
These should be good to go with implementations in babylon, gltf-toolkit and windows mixed reality. Merging now.

**Comment by pjcozzi** [comment]
Awesome, thanks!

**Comment by takahirox** [comment]
Some of the extensions suggest that `image.mimeType` should be "image/vnd-ms.dds" for DDS textures. But it conflicts with glTF core spec. glTF core spec mentions `mimeType` should be "image/jpeg" or
"image/png".

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#imagemimetype

So we should move `"mimeType": "image/vnd-ms.dds"` in extensions?

    "images": [
        {
            "extensions": {
                "MSFT_texture_dds": {
                    "mimeType": "image/vnd-ms.dds"
                }
            },
            "bufferView": 1
        }
    ]

**Comment by lexaknyazev** [comment]
All "enum" properties allow an arbitrary value of the same type, so using `"image/vnd-ms.dds"` doesn't conflict with the schema: 
https://github.com/KhronosGroup/glTF/blob/6c7eafcf9505c09f4fa7276327fe8edb22b7d1fa/specification/2.0/schema/image.schema.json#L15-L28

**Comment by lexaknyazev** [comment]
> That's for extensions?

For extensions and for future minor version updates.

**Pull request merged**
