### PR TITLE
Create KHR_nodes_eyewear_tryon

### PR DESCRIPTION
**Pull request by phadleySnap**
creating folder for new Eyewear try on placement interoperability extension

### CODE REVIEW

**Comment by aaronfranke** [comment]
This PR should be closed, @emackey can you do it?
- Not made by a member of Khronos but uses the KHR prefix.
- This user is brand new to GitHub.
- This isn't a folder, it's a file.
- There is no content here.

**Comment by lexaknyazev** [comment]
It's a placeholder for a potential 3D Commerce extension. The user is a Khronos member.

**Comment by aaronfranke** [comment]
What is the purpose of a placeholder PR with zero context and zero content?

**Comment by emackey** [comment]
Agreed, let's close this PR until there's a readme available.

@phadleySnap Let us know if you need help getting started.  The branch still exists and a new PR can be opened when this is in a more mature state.

**Comment by phadleySnap** [comment]
thanks Ed, the intent of this was mainly just to confirm if I have the
proper permissions / etc in the repo. I will be attempting to update the
repo with the newly proposed eyewear and footwear nodes GLTF extensions
maybe by next week, and will reach out if I run into any challenges. I have
used Github in the past but it has been a few years, so mainly it is just
about me re-educating myself on all the steps.

Thanks,
Patrick

**Pull request closed without merging**
