### PR TITLE
Upgrade wetzel to handle 2020-12 schemas, delete draft4 schemas.

### PR DESCRIPTION
**Pull request by emackey**
For consideration by @lexaknyazev and others.

This consolidates us back to a single set of schemas, dropping draft 4 and moving draft 2020-12 into their place.  A new version of wetzel handles the two main changes: exclusive min/max, and consts instead of enums.

Once CI runs, I plan to diff the output.

### CODE REVIEW

**Comment by emackey** [comment]
Diffing the HTML artifacts from `main` vs. this branch, the date and git hash change of course, and there are two lines in `main` that say this:

```
<p><strong>Format</strong>: uriref</p>
```

Which are replaced on this branch by:

```
<p><strong>Format</strong>: iri-reference</p>
```

This is expected, and I believe this was one motivation for using the newer draft in the first place.

In other news, I tested 2020-12 on a branch of the VSCode plugin, and it seems to perform fine there too.

**Comment by lexaknyazev** [comment]
Before deleting the old schemas, we should check if other Khronos tools (e.g., [glTF-CSharp-Loader](https://github.com/KhronosGroup/glTF-CSharp-Loader)) still use them.

**Comment by emackey** [comment]
@bghgary Is it possible to upgrade the CSharp loader?

Here's an exhaustive list of schema changes:

- The top of every schema file changed slightly (new draft version, new `$id` etc.) but CSharp might not care.
- All occurrences of `"enum" : [ value ]` have changed to `"const" : value`
- `exclusiveMinimum` and `exclusiveMaximum` have changed from a `bool` to the actual value (dropping the old `minimum` and `maximum` fields in cases where they were exclusive). (Example: `camera.perspective.schema.json`)
- In two places, `format` has changed from `uriref` to `iri-reference`  (for example `image.schema.json`).

That's all that changed.

**Comment by bghgary** [comment]
> @bghgary Is it possible to upgrade the CSharp loader?

It's possible for sure, but I don't have the bandwidth to do it any time soon.

**Comment by emackey** [comment]
OK.  Should that hold up this PR?

**Comment by bghgary** [comment]
I'm not sure. I suppose people can checkout a commit before this PR is merged. Can we tag it somehow maybe?

**Comment by emackey** [comment]
No need for a tag.  I updated the C# loader.  https://github.com/KhronosGroup/glTF-CSharp-Loader/pull/37

**Comment by lexaknyazev** [comment]
@bghgary @emackey 
Are glTF-CSharp-Loader updates complete?

**Comment by emackey** [comment]
Yes, thanks to @bghgary who reviewed, tweaked, and merged them.

**Comment by bghgary** [comment]
> Yes, thanks to @bghgary who reviewed, tweaked, and merged them.

Thanks to @emackey who did the actual change. :-)

**Comment by aaronfranke** [comment]
Is there a plan to upgrade the Khronos extension schemas to 2020-12? I noticed they are still using draft-04.

**Comment by javagl** [comment]
This is actually tracked in https://github.com/KhronosGroup/glTF/issues/2049 , but ... with little activity, and ... no volunteers yet 😬

**Pull request merged**
