### PR TITLE
Technique value arrays

### PR DESCRIPTION
**Pull request by lasalvavida**
COLLADA2GLTF fixes for #664

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @lasalvavida!

@lexaknyazev can you review and test?

**Comment by lexaknyazev** [comment]
`material.values` also must be arrays.

**Comment by lasalvavida** [comment]
> material.values elements must also be arrays.

I'm not following. This pull request does that. Shininess and diffuse are placed into arrays. Did I miss something?

**Comment by lexaknyazev** [comment]
Sorry, it's my fault (I've compiled it before merging).

**Comment by pjcozzi** [comment]
I meant this comment for this PR, not #712:

> @lexaknyazev you should now have commit access to this repo so you can just merge this when you are happy.

> You can also start doing work on branches in this repo, instead of a fork if you want, just please don't commit anything to master or 1.0.1 without a pull request.

**Comment by lexaknyazev** [comment]
@lasalvavida 
Converter doesn't enforce arrays in VC.dae: `/techniques/technique0/parameters/light1ConstantAttenuation`:
```js
"light1ConstantAttenuation": {
  "type": 5126,
  "value": 1
},
```

**Comment by lasalvavida** [comment]
Good catch @lexaknyazev. Last commit should fix that

**Comment by lexaknyazev** [comment]
VC.dae, `/materials/_1111/values/transparency` is scalar.

**Comment by lexaknyazev** [comment]
Also:

1. Latest commit makes all GLSL variables (including varyings) arrays, so shaders fail to compile:
 ```
precision highp float;
varying vec3 v_normal[1];
uniform vec4 u_ambient[1];
uniform vec4 u_diffuse[1];
uniform vec4 u_specular[1];
uniform float u_shininess[1];
uniform vec3 u_light0Color[1];
varying vec3 v_light1Direction[1];
varying vec3 v_position[1];
uniform float u_light1ConstantAttenuation[1];
uniform float u_light1LinearAttenuation[1];
uniform float u_light1QuadraticAttenuation[1];
uniform vec3 u_light1Color[1];
varying vec3 v_light2Direction[1];
uniform float u_light2ConstantAttenuation[1];
uniform float u_light2LinearAttenuation[1];
uniform float u_light2QuadraticAttenuation[1];
uniform vec3 u_light2Color[1];
```

2. Latest commit add `"count": 1` to matrix parameters.
 ```js
"modelViewMatrix": {
      "count": 1,
      "semantic": "MODELVIEW",
      "type": 35676
},
"normalMatrix": {
      "count": 1,
      "semantic": "MODELVIEWINVERSETRANSPOSE",
      "type": 35675
},
"projectionMatrix": {
      "count": 1,
      "semantic": "PROJECTION",
      "type": 35676
},
```

**Comment by lasalvavida** [comment]
@lexaknyazev The shader changes are reverted, and this should work properly now. Also, there are some unrelated issues with converting VC from master right now that will be fixed once #732 is merged. For testing, please use my branch: https://github.com/lasalvavida/glTF/tree/technique-value-arrays-nodes-fixed containing the contents of both pull requests, or pull the changes from #732 yourself.

**Comment by lexaknyazev** [comment]
Is it an expected regression (VC.dae)?
```
/meshes/geom-FF01/primitives/3/attributes: Unexpected attribute `TEXCOORD_0` for `technique4` technique or extension.
/meshes/geom-Heli-scout-04/primitives/3/attributes: Unexpected attribute `TEXCOORD_0` for `technique4` technique or extension.
```

**Comment by lasalvavida** [comment]
@lexaknyazev I can double check, but I suspect that is from #636. Unless the collada binds the texture explicitly, we can't tell during generation whether it is used or not, so it isn't safe to assume that it isn't. 

I can add a post-processing stage to check if the generated primitive has unused semantics, but that should be a separate PR.

**Comment by lexaknyazev** [comment]
Closed due to moving COLLADA2GLTF into [separate repo](https://github.com/KhronosGroup/COLLADA2GLTF).
@lasalvavida could you rebase these changes there?

Also see https://github.com/KhronosGroup/COLLADA2GLTF/issues/3.

**Pull request closed without merging**
