### PR TITLE
glTF 2.0: Added default setting for camera.

### PR DESCRIPTION
**Pull request by McNopper**
As mentioned in the telco, added the negative z-axis as default.

### CODE REVIEW

**Comment by recp** [comment]
I think if spec specifies the lens direction (-z) then it must specify right and top too like COLLADA did:

> The camera is defined such that the local +X axis is to the right, the lens looks towards the local -Z axis, and the top of the camera is aligned with the local +Y axis...

**Comment by McNopper** [comment]
Agree. I will just copy and paste the wording.

**Comment by emackey** [comment]
Fixes #956

**Comment by pjcozzi** [comment]
Thanks all!

**Pull request merged**
