### PR TITLE
Docs: Organize converters by input type.

### PR DESCRIPTION
**Pull request by donmccurdy**

### CODE REVIEW

**Comment by lexaknyazev** [comment]
@pjcozzi 
Should we somehow verify readiness/conformance of converters? At least, we should label 2.0-ready ones.

**Comment by pjcozzi** [comment]
This is great, thanks @donmccurdy!

@lexaknyazev in general, I have not been hand testing each glTF adoption, it would be a lot of work; however, I do want to start labeling them as glTF 2.0.  I will soon update the README.md based on #867.

**Comment by xelatihy** [comment]
I was about to ask whether there is a least

1. an OBJ 2 glTF converter
2. a testing harness for glTF 2.0 models

glTF is very hard to implement right!

**Comment by pjcozzi** [comment]
@xelatihy what do you mean by testing harness?  There is a validator, https://github.com/KhronosGroup/glTF-Validator

Also, glTF 2.0 support in obj2gltf is very close, https://github.com/AnalyticalGraphicsInc/obj2gltf/pull/67

**Comment by lexaknyazev** [comment]
> glTF is very hard to implement right!

@xelatihy could you elaborate on this? Maybe we should add more implementation details to the spec.

**Comment by donmccurdy** [comment]
> a testing harness for glTF 2.0 models

I would test with the validator Patrick mentioned, as well as the web preview tools:

- three.js drag and drop viewer: https://gltf-viewer.donmccurdy.com/
- babylon.js viewer: http://www.babylonjs-playground.com/

**Comment by lexaknyazev** [comment]
@donmccurdy 
Only hosted drag-n-drop version is 2.0-ready. Repo with sources will be updated soon.

**Comment by donmccurdy** [comment]
This version of the validator, I assume? http://github.khronos.org/glTF-Validator/

**Comment by lexaknyazev** [comment]
@donmccurdy 
Yes.

**Comment by xelatihy** [comment]
Ok, I'll take a look at these tools. I am doing a full update of yocto_gltf to match the 2.0 spec right now.
When I'll get it done, I will write a post on the difficulties of implementing glTF in strictly type languages.

**Pull request merged**
