### PR TITLE
bglTF benchmarking results and analysis

### PR DESCRIPTION
**Pull request by kainino0x**
Re-created version of #395.

https://github.com/kainino0x/glTF/blob/new-extensions/extensions/CESIUM_binary_glTF/README.md

https://github.com/kainino0x/glTF/blob/new-extensions/extensions/CESIUM_binary_glTF/BenchData/README.md

@pjcozzi

### CODE REVIEW

**Comment by pjcozzi** [comment]
Any thoughts on what I asked in #395:

> Do you want to write a short tech blog about this, e.g., "Do not embed textures in your gzipped models?"

**Comment by kainino0x** [comment]
I wouldn't mind doing that. I would have to do a bit more testing to really understand what is going on with textures in gzipped bgltf, though. The test model that should probably show it best (LargeTex) seems to actually not be very well-compressed to begin with, as gzip seems to reduce the size of the png.

**Comment by pjcozzi** [comment]
OK, let's hold on the blog post until after we do geometric compression, which I think will yield deeper insights here as well.

**Comment by pjcozzi** [comment]
@kainino0x this is ready, right?  No need to hold this up for the blog post.

**Comment by kainino0x** [comment]
Yes, it is ready.

**Pull request merged**
