### PR TITLE
glTF 2.0 draft

### PR DESCRIPTION
**Pull request by lexaknyazev**
Previous discussion was in #784.

* Overview of spec changes: #605
* Direct link to 2.0 spec: https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0
* Direct link to `KHR_technique_webgl` extension stub: https://github.com/KhronosGroup/glTF/tree/2.0/extensions/Khronos/KHR_technique_webgl
* Direct link to branch: https://github.com/lexaknyazev/glTF/tree/2.0

---
**Story so far:**
- rewritten git history of `1.0.1` and `lexaknyazev/master-test` branches with changed paths to `specification/2.0` directory;
- objects-to-arrays syntax change update;
- techniques, shaders, programs were moved to `KHR_technique_webgl` extension;
- updates on JSON encoding and binary data layout
---

**Specification TODOs**
General 2.0 stuff:
- [x] Update wetzel to v4 schema and regenerate property reference, @lasalvavida
- [ ] Update Overview / Reference Card #761, @javagl 
- [x] Make sure everyone is properly acknowledged in the spec, @pjcozzi
- [x] Add notes about scenes #815, @lexaknyazev 
- [x] Publish reasons on syntax and encoding changes #831, @lexaknyazev 
- [x] Elaborate on asset reqs / platform caps #829
- [x] Update date in spec for "Last Updated"

Binary GLB format integration:
- [x] Integrate `.glb` file format as a specification appendix, @lexaknyazev
- [x] Elaborate on referencing `.glb` buffer #828, @lexaknyazev

PBR:
- [x] Integrate PBR, #830, @sbtron, @bghgary
- [ ] Elaborate on PBR conformance #785
- [x] Evaluate multi-UV #742
- [x] Tangent-space storage #812

Skinning & Morphs:
- [x] Skinning update https://github.com/KhronosGroup/glTF/issues/723#issuecomment-254674004
- [x] Sparse Arrays #820, @emilian0
- [x] Integrate morph targets, #164, #210, @emilian0

Other:
- [ ] Close issues labeled [2.0](https://github.com/KhronosGroup/glTF/labels/2.0), all of which should also be labeled `resolved`, @lexaknyazev / @pjcozzi

glTF 2.0 project: #867

### CODE REVIEW

**Comment by pjcozzi** [comment]
Wow, great job, @lexaknyazev!  I will review this a bit today and over the weekend.  Thanks for this detailed work.

**Comment by pjcozzi** [comment]
>  Update wetzel to v4 schema and regenerate property reference

@lasalvavida can you please do this after your COLLADA2GLTF 2.0 updates?  We also need it for 3D Tiles, https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/37 (however, no need to generate that doc now).

**Comment by pjcozzi** [comment]
I added names to items in the above tasklist, https://github.com/KhronosGroup/glTF/pull/826#issue-204961189, please let me know if anything is incorrect.

**Comment by lexaknyazev** [comment]
@pjcozzi 
My proposal in #742 (multi-UV) remains (with 2.0 syntax changes). 
Could PBR team review it?

**Comment by pjcozzi** [comment]
@lexaknyazev could you please review the [2.0 issues](https://github.com/KhronosGroup/glTF/issues?q=is%3Aissue+is%3Aopen+label%3A2.0) and label them `resolved` if they are already included in this PR?

**Comment by pjcozzi** [comment]
> My proposal in #742 (multi-UV) remains (with 2.0 syntax changes).
Could PBR team review it?

Will ask there.

**Comment by pjcozzi** [comment]
@sbtron can any of the [issues labeled PBR](https://github.com/KhronosGroup/glTF/labels/PBR) be closed or combined to help keep us organized?

**Comment by lexaknyazev** [comment]
> @lexaknyazev could you please review the [2.0 issues](https://github.com/KhronosGroup/glTF/issues?q=is%3Aissue+is%3Aopen+label%3A2.0) and label them `resolved` if they are already included in this PR?

GitHub 2.0 issues and tasklist above should be in sync now.

**Comment by bghgary** [comment]
First pass implementation of glTF 2.0 in Babylon.js!

Source: https://github.com/bghgary/Babylon.js/tree/2.0/loaders/src/glTF
Sample scene: https://sbtron.github.io/BabylonJS-glTFLoader/

**Comment by pjcozzi** [comment]
Really nice work @bghgary.  I love the examples!

**Comment by lexaknyazev** [comment]
@bghgary Is it expected to have different results in Firefox and Edge?
Compare:
**Firefox 51**
image

**Edge 38**
image

**Comment by bghgary** [comment]
I'm assuming you mean the dithered "pixel-y" reflections. I think it's because Edge doesn't support EXT_shader_texture_lod. I'll confirm with BabylonJS folks and report back.

**Comment by lexaknyazev** [comment]
> I'm assuming you mean the dithered "pixel-y" reflections.

Yes. 

One more issue: "flat-y" faces.

image

**Comment by bghgary** [comment]
I've confirmed with BabylonJS folks and it is because Edge doesn't support EXT_shader_texture_lod. It should look similar on mobile browsers (I tried on mobile Chrome). I'm asking BabylonJS folks to see if it's possible to make this better when EXT_shader_texture_lod is not available.

**Comment by bghgary** [comment]
> "flat-y" faces
This is also because of EXT_shader_texture_lod.

**Comment by gkv311** [comment]
The commit 8f6eafb "Huge README.md re-edit. Add placeholders for some missing sections." removes all occurrences of UNSIGNED_INT, without mentioning this in commit description - seems to be removed accidentally.

**Comment by lexaknyazev** [comment]
@gkv311 
The only occurrences of UNSIGNED_INT were in "Properties Reference" section, which will be regenerated from JSON-Schemas.

Schemas still have UNSIGNED_INT, e.g.:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/accessor.schema.json#L24

**Comment by gkv311** [comment]
@lexaknyazev 
Ah, I see now - thank you for pointing out.
I was confused that there is no UNSIGNED_INT in the current incomplete version of README.md - e.g. within table "Accessor Attribute Size".

**Comment by lexaknyazev** [comment]
> within table "Accessor Attribute Size"

That's correct. `UNSIGNED_INT` is valid only for indices, not attributes.

**Comment by lexaknyazev** [comment]
@gkv311 
Please see if #858 addresses your concerns.

**Comment by pjcozzi** [comment]
In the first comment, I replaced the project TODOs with a link to the new issue, #867.  The TODOs were:

> **Implementation TODOs**
> 
> - [ ] Cesium, https://github.com/AnalyticalGraphicsInc/cesium/issues/4009, @lasalvavida 
> - [ ] three.js, https://github.com/mrdoob/three.js/issues/10257
> - [ ] BabylonJS
> - [ ] COLLADA2GLTF, https://github.com/KhronosGroup/COLLADA2GLTF/issues/3, @lasalvavida 
> - [ ] obj2gltf, https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/35, @lilleyse 
> - [ ] gltf-pipeline, https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/188, @lasalvavida 
> 
> **Other TODOs**
> - [ ] [Sample models](https://github.com/KhronosGroup/glTF-Sample-Models) for glTF 2.0, @lasalvavida

**Comment by pjcozzi** [comment]
OK to merge this? 😃

**Comment by lexaknyazev** [comment]
@pjcozzi 
OK to delete 2.0 and 1.0.1 branches?

**Comment by pjcozzi** [comment]
Yes, please do.

**Comment by pjcozzi** [comment]
@lexaknyazev now that this is merged, do you want to close all the `resolved` 2.0 issues?

**Pull request merged**
