### PR TITLE
Add some missing types in json schema

### LINKED ISSUE #1584: Node property "name" has no type in the JSON schema
The [name property](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/node.schema.json#L82) in the node schema ([and](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/material.schema.json#L8) [other](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.schema.json#L24) [places](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/texture.schema.json#L16)) has no mandated [type](https://cswr.github.io/JsonSchema/spec/basic_types/), but [the specification says](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#nodename) it's a string.

### PR DESCRIPTION
**Pull request by Ybalrid**
This should fix #1584 
I tried to look at how to specify "any" types for the "extras" property on the JSON Schema docs (https://cswr.github.io/JsonSchema/spec/multiple_types/). We could use "anyOf" and list everything possible, but it seems a bit silly, so I haven't filled in this one.

### CODE REVIEW

**Comment by Ybalrid** [comment]
It was pointed out by #1584 that some basic types are missing in the schemas. I'm going through them right now to see if I can add some of the obviously missing ones

**Comment by Ybalrid** [comment]
Message to maintainers : Please do not merge this until I remove the [WIP] tag on the title 😅

**Comment by Ybalrid** [comment]
All the "name" and "extensions" properties have been set to their proper types

**Comment by emackey** [comment]
Thanks @Ybalrid.  Per discussion in #1584, this is not needed, as these properties inherit from `glTFProperty.schema.json` and `glTFChildOfRootProperty.schema.json` already.

**Comment by Ybalrid** [comment]
Since the changes are unnecessary, I'm closing this PR now.

**Pull request closed without merging**
