### PR TITLE
missing INT

### PR DESCRIPTION
**Pull request by sakrist**
Missing enum for INT type in scheme specification.

### CODE REVIEW

**Comment by bghgary** [comment]
I don't believe anything in the core spec uses it, which is likely the reason why it is not included. Are you thinking it should be there for completeness? Perhaps you have an extension in mind that will use it?

**Comment by sakrist** [comment]
> Are you thinking it should be there for completeness?
Yes :)

**Comment by lexaknyazev** [comment]
To give you some historical perspective:
We've decided that rendering of glTF 2.0 core should be implementable on OpenGL ES 2.0 level hardware with couple extensions (like uint indices and texture shader lod). Because of this, 32-bit attributes aren't supported, i.e., even UINT type could be used only for indices. It's likely that future glTF revisions (2.x) will include 32-bit attribute types from OpenGL ES 3.0 (uint, int, and packed).

**Comment by sakrist** [comment]
@lexaknyazev I understand that you guys  was developing glTF mostly for OpenGL use. 
I think this format is very good and should be more flexible for possible use with other graphics API.

**Pull request closed without merging**
