### PR TITLE
More specific constraints for accessor min and max

### PR DESCRIPTION
**Pull request by pjcozzi**
For https://github.com/KhronosGroup/glTF/issues/593#issuecomment-223636136

@lexaknyazev what do you think?

### CODE REVIEW

**Comment by lexaknyazev** [comment]
Maybe it's too obvious, but should we also demand all values of `min|max` array to align with `accessor.componentType`?

**Comment by pjcozzi** [comment]
It is implicit that the min/max values are bound to the size of `componentType` since they are the min/max of the components which are all of `componentType`.  I don't think we should define them as having the same datatype since they are really a JSON number not a GL datatype.

**Comment by lexaknyazev** [comment]
Sounds fair since `min|max` values are computed from actual typed data.
Will keep validator's check on this anyway.

**Comment by pjcozzi** [comment]
Thanks!

**Comment by lexaknyazev** [comment]
Since both properties are required now, maybe we can replace
>  When both min and max arrays are defined, they have the same length.
with something like
>  Both min and max arrays have the same length.

**Comment by pjcozzi** [comment]
Agreed.  Update the `1.0.1` branch in 16ace82b9bdc1604cee7f7c7f1f782a253bbe268.

**Pull request merged**
