### PR TITLE
Tightening up animations

### PR DESCRIPTION
**Pull request by lexaknyazev**
See https://github.com/KhronosGroup/glTF/issues/704#issuecomment-246082807.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@lexaknyazev can you please come up with a few concise bullets for this so we can update #605?

**Comment by lexaknyazev** [comment]
This PR isn't ready yet: https://github.com/KhronosGroup/glTF/issues/704#issuecomment-246362625

**Comment by pjcozzi** [comment]
Content so far is big +1 from me.  Once we finish the #704 conversation, I'll merge.

**Comment by pjcozzi** [comment]
@lexaknyazev you should now have commit access to this repo so you can just merge this when you are happy.

You can also start doing work on branches in this repo, instead of a fork if you want, just please don't commit anything to `master` or `1.0.1` without a pull request.

**Comment by pjcozzi** [comment]
@lexaknyazev looks good, but doesn't the spec README.md need to be updated in addition to the schema files?

**Comment by lexaknyazev** [comment]
Of course, I'll update readme before merging. Do we need to clarify anything else here?

**Comment by pjcozzi** [comment]
No, I think it looks great.

**Comment by pjcozzi** [comment]
@lexaknyazev is this ready now given 795580c39bcc1f57731da54add634a553229bc97?

**Comment by lexaknyazev** [comment]
Not yet, I'm updating descriptions and examples now.

**Comment by lexaknyazev** [comment]
@pjcozzi please review updated README.md and schema files.

**Comment by pjcozzi** [comment]
Looks good, thanks @lexaknyazev!

Can you please update #605 (just edit the main comment) with a few bullets for this?

**Comment by lexaknyazev** [comment]
Done

**Pull request merged**
