### PR TITLE
test_glTF

### PR DESCRIPTION
**Pull request by dzbkqsw**
试一下

### CODE REVIEW

**Comment by pjcozzi** [comment]
@dzbkqsw is this a translation of the glTF spec to Chinese?

If so, it could be a great contribution, but we would want this to be a separate document, and not have both the English and Chinese version in the same .md file.

**Comment by realvictorprm** [comment]
Hm this only affects the first version of glTF. Would be awesome to see the second version translated too

**Comment by pasu** [comment]
update to the latest

**Comment by emackey** [comment]
Translations are most welcome, but need to be placed in separate documents.  I'm going to close this one since it's fairly old, but please do open a new PR if these changes are made.  Thanks!

**Pull request closed without merging**
