### PR TITLE
Clarify that array parameters are not the same as vectors

### PR DESCRIPTION
**Pull request by pjcozzi**
For https://github.com/KhronosGroup/glTF/issues/563#issuecomment-210993081

@lexaknyazev what do you think of this clarification?

### CODE REVIEW

**Comment by lexaknyazev** [comment]
That clears possible ambiguity. 
Two more points:

1. Should `parameter.count` property be allowed for attribute parameters?
2. The only use of `count` property in sample models is `jointMat` parameter with `JOINTMATRIX` semantic. Maybe it should be stated in spec, that parameters with other spec-defined semantics can't have `count` property.

**Comment by pjcozzi** [comment]
See #258.

In Cesium, we currently only support attribute arrays for skinning: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L1976-L1981

Actually, the same is true for uniforms: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2508-L2511

We want it to be as easy as possible to write a correct (and _fast!_) loader for glTF.  At the same time, we don't want to limit widely used GL features.

Given this, do you think the best trade off is to only allow `count` for `JOINTMATRIX` to simplify what it takes to write a complete loader?

Also, a change here will need to be a separate PR since it would need to be glTF 1.0.1, not just a clarification in the 1.0 spec.

**Comment by lexaknyazev** [comment]
> We want it to be as easy as possible to write a correct (and fast!) loader for glTF. At the same time, we don't want to limit widely used GL features.

Spec doesn't define how to treat arrays for known semantics such as `PROJECTION` or `MODELVIEW`. So I think it would be safe to say that all uniform semantics except `JOINTMATRIX` can't be arrays (or define that behavior otherwise). There are unrestricted custom semantics for application-specific use.

As for attribute arrays I honestly don't quite understand what it means since GLSL explicitly forbids them.

**Comment by pjcozzi** [comment]
All sounds good, updated in d2f69457dc46a9c00307c27faf9e4cde4a5896d0.

For reference, from Section `4.3.3 Attribute` of the [GLSL spec](https://www.khronos.org/registry/gles/specs/2.0/GLSL_ES_Specification_1.0.17.pdf):

 > Attribute variables cannot be declared as arrays or structures.

**Comment by pjcozzi** [comment]
@lexaknyazev OK to merge this?

**Comment by lexaknyazev** [comment]
Lgtm
Is it intended that this PR goes to `master`, while https://github.com/KhronosGroup/glTF/commit/d2f69457dc46a9c00307c27faf9e4cde4a5896d0 goes to `1.0.1`?

**Comment by pjcozzi** [comment]
Yes, I think it is pretty clear-cut that this is just a clarification to the spec, where d2f69457dc46a9c00307c27faf9e4cde4a5896d0 is really a spec change.  It is a subtle call here, but I'd rather stay conservative when adding clarifications to the 1.0 spec.

**Comment by pjcozzi** [comment]
@lexaknyazev is this ready to merge?

**Comment by lexaknyazev** [comment]
:+1:

**Pull request merged**
