### PR TITLE
Updated quantized attributes extensions

### PR DESCRIPTION
**Pull request by lasalvavida**
For #610 and #588 
@pjcozzi @mlimper

### CODE REVIEW

**Comment by pjcozzi** [comment]
+1 from me.

@lasalvavida also add an `Acknowledgements` section at the bottom (like the glTF spec) and include @lexaknyazev.

@mlimper can you confirm and I will merge?

**Comment by lasalvavida** [comment]
Updated

**Comment by mlimper** [comment]
Confirmed, thanks for updating and merging

**Comment by pjcozzi** [comment]
@mlimper did you also see the discussion in https://github.com/KhronosGroup/glTF/issues/593#issuecomment-223651243 where I want to change

> These properties are required if the quantized attribute uses the POSITION semantic. This simplifies the client implementation where `min` and `max` are used to compute bounding volumes.

to always requiring `decodedMax` and `decodedMin` since `max`/`min` will always be required in glTF 1.0.1.  What do you think?

**Comment by mlimper** [comment]
It doesn't seem to cause a lot of work for writer implementations, but it looks like it would make reader implementations more straightforward.
+1!

**Comment by pjcozzi** [comment]
> It doesn't seem to cause a lot of work for writer implementations, but it looks like it would make reader implementations more straightforward.
+1!

Great!

@lasalvavida can you make the update?

Is anything else needed before merging?

**Comment by lasalvavida** [comment]
If nobody else has any comments, this should be ready to go.

**Comment by pjcozzi** [comment]
Thanks for all your work on this @lasalvavida and @mlimper!

**Comment by lexaknyazev** [comment]
Should [L96](https://github.com/KhronosGroup/glTF/blame/d17eb2b1f7d6a7c14709ac0925cb4bdecb105ef0/extensions/Vendor/WEB3D_quantized_attributes/README.md#L96) say "two" instead of "three", or one example is missing?

**Comment by lasalvavida** [comment]
Nope I missed that, good catch @lexaknyazev. There were three, but there are two now. I will put in a PR for that.

**Pull request merged**
