### PR TITLE
Update coordinate system and units section with forward convention.

### PR DESCRIPTION
**Pull request by bghgary**
See https://github.com/KhronosGroup/glTF/issues/1043#issuecomment-339132697

### CODE REVIEW

**Comment by bghgary** [comment]
@pjcozzi @lexaknyazev @emackey @javagl Would like some feedback on the wording and/or if we need to explain this more.

**Comment by bghgary** [comment]
I'll look into adding something, though the boom box model is a good example already as it has a clear front and back.

**Comment by pjcozzi** [comment]
A screenshot with overlaid axes of any of these models in the spec would be good.

**Comment by bghgary** [comment]
Ah, okay. I'll check with tech art.

**Comment by bghgary** [comment]
@pjcozzi How's this? I can add a sample model for this as well.

**Comment by pjcozzi** [comment]
Ah, good idea for the sample model.

The figure looks good but shouldn't we label the axes with X, Y, and Z?

**Comment by bghgary** [comment]
We talked about this. We thought it was clear enough that red is X, green is Y, and blue is Z, but labels won't hurt.

cc @PatrickRyanMS

**Comment by bghgary** [comment]
@pjcozzi I've updated it with axis labels.

**Comment by pjcozzi** [comment]
Perfect!

**Pull request merged**
