### PR TITLE
Uupdated to 1 node per mesh, 1 accessor per skin.

### PR DESCRIPTION
**Pull request by zellski**
The replaced image suggests a 1-to-N relationship for nodes to meshes, and similarly from skin to accessors.

The font in this PPT export is a little heavier than in the .png being replaced; perhaps because I'm on a Mac. I'm not sure which I prefer; let me know if anybody prefers the older, lighter look.

See #1170.

### CODE REVIEW

**Comment by pjcozzi** [comment]
+1.  Thanks!

Anyone else want to look at this?  @lexaknyazev?

**Comment by bghgary** [comment]
The new image seems to be a screenshot of the entire slide which I don't think is what you want. Other than that, LGTM.

**Comment by zellski** [comment]
What! I spent half an eternity cropping it.

I must’ve uploaded the wrong file. Will fix.

**Comment by zellski** [comment]
Okay, let's try this again. Updated to properly cropped version.

**Comment by pjcozzi** [comment]
Thanks again @zellski!

**Pull request merged**
