### PR TITLE
Regenerated property reference

### PR DESCRIPTION
**Pull request by sbtron**
Regenerated reference based on latest Wetzel and schema

### CODE REVIEW

**Comment by lexaknyazev** [comment]
Couple notes:
- Reference sections have different order than ToC list (e.g. `sparse.indices` are located after `images`). Was it intentional?
- [`animation.sampler`](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/animation.sampler.schema.json#L3) has wrong title (compare to [`animation.channel`](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/animation.channel.schema.json#L3)).

**Comment by sbtron** [comment]
The generator isn't smart enough to lay out the paragraphs correctly. I believe it was the same earlier we will have to tweak it manually. 
animation sampler title seems like a json schema issue?

**Comment by emackey** [comment]
> The generator isn't smart enough to lay out the paragraphs correctly

Not sure I follow.  What needs to happen to the generator?

**Comment by lexaknyazev** [comment]
> animation sampler title seems like a json schema issue

Yes, schema file should be tweaked.

**Comment by pjcozzi** [comment]
> Reference sections have different order than ToC list (e.g. sparse.indices are located after images). Was it intentional?

Probably an oversight with manual edits.

**Comment by pjcozzi** [comment]
> I believe it was the same earlier we will have to tweak it manually.

Yes, I did a lot of hand editing for the 1.0 spec.

**Comment by emackey** [comment]
Also, next time this is re-run, try adding the `-a` (`--autoLink`) option, such that intra-schema references are linked together.

**Comment by lexaknyazev** [comment]
@sbtron 
JSON title fixed with cad4e6f1642fe9348ababfd7327b4245fb96e5e8.

**Comment by lexaknyazev** [comment]
@sbtron @emackey 

Could Wetzel generate full names for nested objects? This would fix both ordering issue as well as having two `samplers`:

- `accessor`
  - `accessor.sparse`
     - `accessor.sparse.indices`
     - `accessor.sparse.values`
- `animation`
  - `animation.sampler`
  - `animation.channel`
      - `animation.channel.target`

Otherwise, we could manually change all titles in schema files.

**Comment by emackey** [comment]
This could eventually happen, it won't be immediate though.

**Pull request merged**
