### PR TITLE
Add non-normative section for point/line materials.

### LINKED ISSUE #1277: Point size and line width
When using primitive mode POINTS, LINES, LINE_LOOP, LINE_STRIP, what is the expected point size and line width? Should they be 1?

### PR DESCRIPTION
**Pull request by donmccurdy**
Resolves #1277.

### CODE REVIEW

**Comment by pjcozzi** [comment]
LGTM.

Does anyone else want to review?

**Comment by pjcozzi** [comment]
I'll merge today unless there are any other comments.

Thanks @donmccurdy!

**Comment by donmccurdy** [comment]
Rephrased the line in question:

* POINTS and LINES should have widths of 1px in viewport space.

**Comment by pjcozzi** [comment]
Thanks @donmccurdy @bghgary!

**Pull request merged**
