### PR TITLE
JOINTMATRIX should be a uniform semantic

### LINKED ISSUE #592: Spec inaccurately lists JOINTMATRIX as an attribute semantic
In the [spec](https://github.com/KhronosGroup/glTF/tree/master/specification#parametersemantic), the semantic JOINTMATRIX is listed with the attribute semantics, but in the [CesiumMan](https://github.com/KhronosGroup/glTF/blob/0dd42b0c5e6db4c1eb7571739d01302cc40040ad/sampleModels/CesiumMan/glTF/CesiumMan.gltf#L2139) sample model, it is used as a uniform semantic.

I suspect the spec just needs a fix, @pjcozzi?

### PR DESCRIPTION
**Pull request by lasalvavida**
Fixes #592

### CODE REVIEW

**Comment by lasalvavida** [comment]
@pjcozzi take a look at this when you get a chance

**Comment by pjcozzi** [comment]
Looks good.  Can you also update the JSON schema files?

**Comment by lasalvavida** [comment]
@pjcozzi Done. That's all the files that mention JOINTMATRIX; let me know if you think I missed anything.

**Comment by pjcozzi** [comment]
👍

**Comment by lexaknyazev** [comment]
[Validator](https://lexaknyazev.github.io/gltf-demo/) updated.

**Comment by lasalvavida** [comment]
Awesome, thanks @lexaknyazev

**Pull request merged**
