### PR TITLE
KHR_materials_specular extension branch.

### PR DESCRIPTION
**Pull request by UX3D-nopper**

### CODE REVIEW

**Comment by bhouston** [comment]
I've made some minor changes in this fork:
https://github.com/bhouston/glTF/tree/extensions/KHR_materials_specular/extensions/2.0/Khronos/KHR_materials_specular

Specifically instead of using the unreal engine parameterization of specifying F0 directly, I've proposed adopting "specularIOR".  I have also suggested "specularFActor" which allows you to scale the grazing angle max Fresnel result.  And lastly "specularColor" which is a tint to the overall specular reflection.  "specularFactor" and "specularColor" could be combined in an implementation but both Autodesk and Dassault keep them separate for easy of use for artists.

**Comment by bhouston** [comment]
I just noticed that my proposal was nothing more than the existing competing specular proposal: https://github.com/KhronosGroup/glTF/pull/1719  I support that one over this one.

**Comment by kofi-de-com** [comment]
+1 for this extension. Aligns well with Blender's workflow.

**Comment by donmccurdy** [comment]
@kofi-de-com is there something specific about this proposal that you prefer over the version in #1719? Or do you mean a general +1 for either?

**Comment by kofi-de-com** [comment]
@donmccurdy it turned from a +1 for the specific proposal into a +1 for the extension in general.
At first glance it seemed easier to not have a specularColor feature. I've since then changed my mind and would suggest to move forward with #1719.
Background: As far as I can tell Blender does not properly support specular color tinting as suggested in #1719. It's specular tint value defaults to 0 (which behaves something like specularColorFactor(1, 1, 1)). If specular tint in Blender is set to 1, it looks like specularColorFactor(baseColor.r, baseColor.g, baseColor.b). This means Blender's material values can be converted at export time to work with #1719.

**Comment by UX3D-nopper** [comment]
closed in favor for https://github.com/KhronosGroup/glTF/pull/1719

**Pull request closed without merging**
