### PR TITLE
Explain why texture.source is not always required

### LINKED ISSUE #1226: 'texture.source' property is not required, but no default value is specified?
From the spec:

| |Type | Description | Required |
| --| -- | -- | -- |
source | integer | The index of the image used by this texture. | No

I can't seem to find any information on how a complying GLTF2 loader should actually behave if texture.source is not defined.
Usually, the spec states a default value to be used instead, as in texture.sampler:

| |Type | Description | Required |
| --| -- | -- | -- |
sampler	| integer |	The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering should be used. |	No

However, I can't find any information on a default value for texture.source, neither in the properties reference nor in the *Texture Data* section.

The only other options I might be missing are that texture.source is not needed when some
other properties are set (but I can't find anything on that either, and it would be kind of absurd to exist anyway) or that the texture is supposed to be filled with zeroes, much like a buffer without uri (or that's at least my understanding of how a buffer without uri behaves).

I believe the intended behavior to be simply using the first / only image in the GLTF file *per default* as the source, but I am not sure.

Can someone please clarify this?

Thank you in advance.

### PR DESCRIPTION
**Pull request by emackey**
Fixes #1226.

### CODE REVIEW

**Comment by lexaknyazev** [comment]
Should textures with nor `source` neither `extensions` be invalid?

**Comment by emackey** [comment]
Good question.  Would there be some future way to supply a texture that didn't place an extension directly on the texture object, but still used a texture object?  I don't... think so?

Current implementations mostly throw an exception if a source isn't supplied one way or another.

**Comment by lexaknyazev** [comment]
- It could be app-specific `extras`.
- An engine could use false color or other predefined value for missing textures.

**Comment by emackey** [comment]
Sure.  So I don't think we can tighten the schema-level field requirements on this.  Is my description here good enough then, or does it need to change to indicate that engines are free to use default colors or even reject models that don't properly specify a source?  (Where "properly" in my mind is either specifying it with the source property, or marking a WebP or DDS type extension under "extensionsRequired").

The WebP extension for example specifically states that it must be placed in `extensionsRequired` in order for `source` to be left undefined.

**Comment by emackey** [comment]
Would this make sense?

#### texture.source

The index of the image used by this texture. When undefined, it is expected that an extension or other mechanism will supply an alternate texture source.

**Comment by emackey** [comment]
@lexaknyazev Is this OK?

**Comment by lexaknyazev** [comment]
Should we suggest any behavior in case when nor `source` neither `extensions` are present?
If not, this looks good to me.

**Comment by emackey** [comment]
How about this:

The index of the image used by this texture. When undefined, it is expected that an extension or other mechanism will supply an alternate texture source, otherwise the reader may throw an exception.

**Comment by emackey** [comment]
Updated as we discussed.

**Pull request merged**
