### PR TITLE
Add Tiny glTF loader and gltf-walker

### PR DESCRIPTION
**Pull request by pjcozzi**
Organizes the loader section of README.md by language.

Adds links to awesome work by @syoyo and @ksons.

### CODE REVIEW

**Comment by syoyo** [comment]
Super cool! Thanks!

**Comment by vinjn** [comment]
Note: assimp glTF importer is also working for static meshes.
https://github.com/assimp/assimp/blob/master/code/glTFImporter.cpp

**Comment by pjcozzi** [comment]
Great news, @vinjn!  I added it to the list in #514.

Are you aware of any other glTF implementations we should include?

**Comment by vinjn** [comment]
I will inform you once I see them.

**Pull request merged**
