### PR TITLE
Clarify camera parameters

### LINKED ISSUE #1663: xmag and ymag should be clarified to be width/2 and heigth/2
Also the tutorial is misleading:
https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_016_Cameras.md

### PR DESCRIPTION
**Pull request by lexaknyazev**
Fixes #1663.

### CODE REVIEW

**Review by javagl — COMMENTED** [review]
The clarification of the aspect ratio is good. A bit more generally, I sometimes wondered whether the `aspectRatio` of the camera or the *actual* aspect ratio of the viewport should be used. There once was a mail thread, where I sent around a test ("Re: [3dformats] Camera scale test model", 30.06.2021, 20:44), including these images:

babylonjs 002 Perspective scaled uniformly

threejs 002 Perspective scaled uniformly

showing that babylon seems to use the `aspectRatio`, whereas three.js seems to use the viewport aspect ratio. 

Given that clarification, one could file an issue in three.js, pointing to this section.

---

Regarding the definition of the variables: This makes sense, but ... is now a bit redundant. They already had been defined _after_ the equations. We might consider merging these bullet point lists, so that we only have _one_ list, with all information, like

- `a` be the aspect ratio (width over height) of the field of view, which is given as `camera.perspective.aspectRatio` or from the aspect ratio of the current viewport
- `y` be the vertical field of view in radians, given by `camera.perspective.yfov` 

... 

But I don't have a strong opinion here...

**Comment by emackey** [comment]
> We might consider merging these bullet point lists, so that we only have _one_ list, with all information

I like this idea.  I'm not opposed to merging as-is, or with that change.

**Comment by donmccurdy** [comment]
three.js [does use the camera's aspect ratio](https://github.com/mrdoob/three.js/blob/b1ede8160b5aefe18c7ec29f2af80f78b0ffd911/examples/js/loaders/GLTFLoader.js#L3136-L3144), but this is only going to give the expected result in a viewer if the viewport also has that same aspect ratio. It rarely does.

> ...client implementations **SHOULD NOT** crop or perform non-uniform scaling ("`stretching`") to fill the viewport.

What is this saying a client _should_ do? scale uniformly and leave part of the viewport unrendered?

**Comment by lexaknyazev** [comment]
> What is this saying a client _should_ do? scale uniformly and leave part of the viewport unrendered?

I think this depends on an application. A simple scene renderer should scale uniformly and leave the extra viewport regions unused (or repurpose them for something else). An application that uses multiple active windows may resize the viewport to match the camera's aspect ratio.

**Review by javagl — APPROVED** [review]
I think having the formal definitions and the respective property in one block (thus, _defining_ each variable only once) is nicer.

**Pull request merged**
