### PR TITLE
fixed broken jgltf links

### PR DESCRIPTION
**Pull request by sjfricke**
also added the jgltf-validator

### CODE REVIEW

**Comment by javagl** [comment]
Thanks, I think it's OK to merge this. 

(The validator was not mentioned there originally, because it is not really intended for public use. The task to align this validator to yours (in terms of the output format etc.) is still on my TODO list - together with the task to update the readme and put the JglTF libraries into a table, to follow the pattern that is used for the other libraries). But these currently do not have highest priority)

**Comment by pjcozzi** [comment]
Thanks again @sjfricke!  BTW what are you building with glTF?

**Comment by sjfricke** [comment]
@pjcozzi Currently hacking around with WebGL2 and WASM and finally had some time to read up on glTF spec and tools since I learned about it at SIGGRAPH17 and realized it solves all the pipeline nightmares I have got trying to load assets via the web in past

**Comment by pjcozzi** [comment]
@sjfricke very cool, please keep us posted on your progress!  More PRs are welcome and also feel free to chime in at #1058.

**Pull request merged**
