### PR TITLE
Remove Catmull-Rom spline from the specification

### PR DESCRIPTION
**Pull request by bghgary**
The working group last week agreed that Catmull-Rom should be removed from the spec. This is a PR to remove it. Let's discuss how to proceed.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @bghgary!

**Everyone** - did anyone implement Catmull-Rom splines in a glTF exporter or importer?  We are not aware of any in the wild so I think this PR may just be as simple as it currently is with perhaps a brief note about why Catmull-Rom splines were removed.  If there **are** implementations, perhaps we can provide some migration advice.

@javagl does this require any updates to the [glTF Tutorial Series](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/README.md)?  I think not.

@lexaknyazev @emackey does this require any updates to [glTF Sample Models](https://github.com/KhronosGroup/glTF-Sample-Models)?  I think not.

Is there anything else we should consider before moving this forward?

**Comment by emackey** [comment]
Our sample models don't use anything other than `"interpolation": "LINEAR"`.  😞

**Comment by emackey** [comment]
The Khronos Blender exporter apparently does Cubic splines, not Catmull-Rom, but I haven't tried it yet.

**Comment by emackey** [comment]
Looks like Three at least processes the `CATMULLROMSPLINE` enum, albeit with some other spline implementation, in https://github.com/mrdoob/three.js/pull/11825.  /cc @donmccurdy @zellski 

Looks like this could be fixed by removing one line of code.

**Comment by javagl** [comment]
@pjcozzi  The https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_007_Animations.md sections only shows a `LINEAR` example as well. More details about STEP/CUBICSPLINE could/should be added. But I'm glad that CATMULLROM can be omitted.

**Comment by pjcozzi** [comment]
@emackey ha, sounds good for three.js!  Do you happen to know what Cesium does?

**Comment by emackey** [comment]
Cesium has a `CatmullRomSpline` math class that is never referenced by the glTF implementation.

For glTF, I only see one reference in the code to examining the contents of an `interpolation` field, and here it's only branching `LINEAR` off from all other (apparently spline-based) interpolations.

https://github.com/AnalyticalGraphicsInc/cesium/blob/cb237a32a1c9934d19824e0081828282995291b2/Source/Scene/ModelAnimationCache.js#L128

I don't fully understand the above code yet, but it's at least clear there's no implementation of Catmull-Rom for glTF in Cesium.  The enum name is missing from the source tree.

**Comment by zellski** [comment]
My in-progress spline support for FBX2glTF only uses the full cubics. I was
not on the call but I assume the decision is based on the fact that C-R is
mostly a convenience? Although it could be seen as a compression format too
— right? For curves that satisfy the requirements, in models heavy with
animation data, it could be substantial savings...

**Comment by bghgary** [comment]
@zellski 
> C-R is mostly a convenience?
We had a couple threads discussing this in the working group. The gist is that we didn't know anyone who implemented it and there were issues with overshooting if it's intended for authored animations.

> it could be seen as a compression format
True. The Draco compression team is already looking into this, so we decided it would be best to let them decide what compression method is best for compressing animation curves.

**Comment by pjcozzi** [comment]
Thanks again @bghgary and everyone who looked into this!

**Pull request merged**
