### PR TITLE
Skinning fixes for 1.0.1

### PR DESCRIPTION
**Pull request by lexaknyazev**
See #624

### CODE REVIEW

**Comment by pjcozzi** [comment]
All looks good to me.  Will get more feedback on Wednesday morning, and merge then.

**Comment by pjcozzi** [comment]
Thanks @lexaknyazev!  Can you please provide a concise description for this that I can add to #605?

**Comment by tparisi** [comment]
I think these changes all look good, clarifying language. Maybe we do one more pass before merging? @pjcozzi  did you have a look?

**Comment by pjcozzi** [comment]
@lexaknyazev did you see this:

> Can you please provide a concise description for this that I can add to #605?

**Comment by lexaknyazev** [comment]
The only change (not clarifications) could be described as

> Skeleton hierarchies (nodes containing `jointName`) must be separated from non-skeleton hierarchies.

**Comment by pjcozzi** [comment]
Thanks!

**Pull request merged**
