### PR TITLE
Add schema reference doc to spec

### PR DESCRIPTION
**Pull request by pjcozzi**
This is a pull request into `spec-1.0`.  Do not merge this yet.  This is for feedback on a preview of what the reference doc will look like.  For example, see the [accessor](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-accessor).

Note that any edits to the text of the schema reference doc should also be made to the schema itself (the `*.schema.json` files in the `schema` sub-directory) since we are auto-generating (then tweaking) the doc from the schema with [wetzel](https://github.com/AnalyticalGraphicsInc/wetzel).

### CODE REVIEW

**Comment by tparisi** [comment]
Looks pretty awesome to me, cosmetically. 

Is there any way to include ranges and/or allowable values for each property?

**Comment by pjcozzi** [comment]
> Is there any way to include ranges and/or allowable values for each property?

Yes, it is in the details for each property under the table.

**Comment by tparisi** [comment]
Riight. I blew right by those on my first read. Well then I think this is REALLY good. Nice tool.

**Comment by pjcozzi** [comment]
Added reference doc for [animations](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-animation).

**Comment by pjcozzi** [comment]
Added reference doc for [asset](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-asset).

**Comment by pjcozzi** [comment]
Added reference doc for [buffer](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-buffer).

**Comment by pjcozzi** [comment]
Added reference doc for [bufferView](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-bufferView).

**Comment by pjcozzi** [comment]
Added reference doc for [camera](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-camera).

**Comment by tparisi** [comment]
@pjcozzi are we ready to merge or are you still streaming in changes?

**Comment by pjcozzi** [comment]
I'm still adding reference doc.  I'll until tomorrow night - maybe sooner if it goes well.

**Comment by pjcozzi** [comment]
Added reference doc for [image](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-image).

**Comment by pjcozzi** [comment]
Added reference doc for [material](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-material).

**Comment by pjcozzi** [comment]
Added reference doc for [mesh](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-mesh).

**Comment by pjcozzi** [comment]
Added reference doc for [node](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#node).

**Comment by pjcozzi** [comment]
Added reference doc for [program](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#program).

**Comment by pjcozzi** [comment]
Added reference doc for [sampler](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#sampler).

**Comment by pjcozzi** [comment]
Added reference doc for [scene](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#scene).

**Comment by pjcozzi** [comment]
Added reference doc for [shader](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#shader).

**Comment by pjcozzi** [comment]
Added reference doc for [skin](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#skin).

**Comment by pjcozzi** [comment]
Added reference doc for [texture](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#texture).

**Comment by pjcozzi** [comment]
Added reference doc for the [root object](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-glTF).

**Comment by pjcozzi** [comment]
Added reference doc for [technique](https://github.com/KhronosGroup/glTF/blob/1.0-reference/specification/README.md#reference-technique).

**Comment by pjcozzi** [comment]
Merging into `spec-1.0`, then I am going to make a `spec-1.0-copyright` branch for copyedits.

**Pull request merged**
