### PR TITLE
Fix animations

### LINKED ISSUE #551: COLLADA2GLTF can't convert Maya's moved group pivot information correctly.
Hi there.

I tried latest COLLADA2GLTF, but I found a little weird covert result.

Look at this maya scene file (group_pivot.mb in attached zip file).
In this scene, there is a group whose pivot position is moved to (0, 5, 0).
You can see this animation scene at https://youtu.be/-BME5VZRDUQ

I exported this scene to collada file (group_pivot.dae) using ColladaMaya exporter.
I checked that this collada file is correct. Because MacOS preview function showed correct animation.
https://youtu.be/NwhLpZD2gBM

Then, I converted this collada file to gltf file (group_pivot_original.gltf, group_pivot.bin, group_pivot0FS.glsl and group_pivot0VS.glsl) using COLLADA2GLTF.
But Its data (group_pivot_original.gltf) seem wrong.

This video is the result of group_pivot_original.gltf using my original WebGL library, GLBoost. It’s wrong animation as you can see.
https://youtu.be/ZapNp3LNB6A

I think that the cause is the following part (in group_pivot_original.gltf).
```group_pivot_original.gltf
    "nodes": {
        "_group1": {
            "children": [
                "_group1_pCube1"
            ],
            "name": "group1",
            "rotation": [
                0,
                0,
                0.707107,
                0.707107
            ],
            "scale": [
                1,
                1,
                1
            ],
            "translation": [       <- ?
                5,
                5,
                0
            ]
        },
        "_group1_pCube1": {
            "children": [],
            "matrix": [       <- ?
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                1
            ],
```

So, I fixed the data (group_pivot_fixed.gltf) as following.

```group_pivot_fixed.gltf
    "nodes": {
        "_group1": {
            "children": [
                "_group1_pCube1"
            ],
            "name": "group1",
            "rotation": [
                0,
                0,
                0.707107,
                0.707107
            ],
            "scale": [
                1,
                1,
                1
            ],
            "translation": [
                0,
                5,
                0
            ]
        },
        "_group1_pCube1": {
            "children": [],
            "matrix": [
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                -5,
                0,
                1
            ],
```

Then, My GLBoost Renderer showed correct Animation.
https://youtu.be/zyV3JKvEZqE

In conclusion, I think that COLLADA2GLTF should export like group_pivot_fixed.gltf, not  group_pivot_original.gltf.
Or, If there is a pivot infomation in glTF spec. COLLADA2GLTF should export it.
I guess that this problem is caused by COLLADA2GLTF’s bug, not my GLBoost library’s bug.

[group_pivot.zip](https://github.com/KhronosGroup/glTF/files/177024/group_pivot.zip)

### PR DESCRIPTION
**Pull request by lasalvavida**
Fixes #551, #580. 

Still a WIP and needs to be reviewed. ~~It seems like some of the rotation from #580 is a little off, so I'm still looking at that.~~

Modifies the output glTF node hierarchy so that COLLADA transforms that are targets of animations have their behavior preserved.

* [x] Add back support for instance nodes (should be trivial)
* [x] LookAt matrix?

### CODE REVIEW

**Comment by lasalvavida** [comment]
Animation jitter is fixed. Coin drop and group pivot now convert correctly.
[test.zip](https://github.com/KhronosGroup/glTF/files/420710/test.zip)

**Comment by lasalvavida** [comment]
Instance nodes are supported again.

**Comment by lasalvavida** [comment]
There is some jerkiness in CesiumMan and BrainStem after conversion; looking into it.

**Comment by lasalvavida** [comment]
Animation jerkiness is fixed. Decomposed model matrix animations were switching chiralities of the quaternions. Now it picks the quaternion that is the least different from the last one.

**Comment by lasalvavida** [comment]
Okay, this should be ready for a look.

**Comment by emadurandal** [comment]
@lasalvavida Thank you for the fixing work!
But unfortunately, build task failed as for me (OSX El Capitan, Xcode 7.3.1).
Are there any other necessary things with your branch to build?

```
CompileC COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/animationConverter.o convert/animationConverter.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler

    cd /Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF

    export LANG=en_US.US-ASCII

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=124 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Debug\" -DLIBXML_STATIC_FOR_DLL -DUSE_OPEN3DGC -DUSE_LIBPNG -DSTATIC_COLLADA2GLTF -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.11 -g -Wno-sign-conversion -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/lib/Debug/include -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/GLTF -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/JSON -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/shaders -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/helpers -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/convert -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/assetModifiers -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/json/include/rapidjson -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADAFramework/include -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/OpenCOLLADA/GeneratedSaxParser/include -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/extensions/o3dgc-compression -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/o3dgc/src -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/o3dgc/src/o3dgc_common_lib/inc -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/o3dgc/src/o3dgc_encode_lib/inc -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/dependencies/o3dgc/src/o3dgc_decode_lib/inc -I/Library/Frameworks/Mono.framework/Headers -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/DerivedSources/x86_64 -I/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/lib/Debug -std=c++11 -fPIC -MMD -MT dependencies -MF /Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/animationConverter.d --serialize-diagnostics /Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/animationConverter.dia -c /Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/convert/animationConverter.cpp -o /Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/animationConverter.o

clang: error: no such file or directory: '/Users/emadurandal/ESDocs/Programs/WebGL/glTF/COLLADA2GLTF/convert/animationConverter.cpp'

clang: error: no input files



** BUILD FAILED **
```

**Comment by lasalvavida** [comment]
It looks like I missed a reference to animationConverter in a cmake file somewhere, I'll check.

**Comment by lasalvavida** [comment]
I see what happened. You do need to re-run cmake on this branch. Your Xcode project is still referencing a file that was removed, so the project needs to be regenerated.

**Comment by emadurandal** [comment]
I succeeded build. thank you!
Then I can try this version.

**Comment by emadurandal** [comment]
I tried this proposal version.

https://youtu.be/fWX0sln21pk (OK. fixed!)

Then, I tried another example.

https://youtu.be/YA0b9FWModc (Maya data)
https://youtu.be/t5iCW2IM61E (Current master)  confirm the problem.
https://youtu.be/1HudbdnM59M (lasalvavida:fix-animations)     OK fixed!

Looks very good to me.

I attached maya file.
[snake.mb.zip](https://github.com/KhronosGroup/glTF/files/421540/snake.mb.zip)

**Comment by lasalvavida** [comment]
Awesome @emadurandal! Thanks for the testing.

**Comment by pjcozzi** [comment]
@tfili can you please review this when you are back in the office?

**Comment by lasalvavida** [comment]
@tfili Can you look at this when you get a chance?

**Comment by lasalvavida** [comment]
@tfili Bump

**Comment by tfili** [comment]
@lasalvavida It's next on my list.

**Comment by tfili** [comment]
@lasalvavida Cesium Man worked fine. I converted CesiumAir and get the following when trying to render

```
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'matrix' of undefined
TypeError: Cannot read property 'matrix' of undefined
    at getTransform (http://localhost:8080/Source/Scene/Model.js:1419:25)
    at computeBoundingSphere (http://localhost:8080/Source/Scene/Model.js:1198:34)
    at Model.update (http://localhost:8080/Source/Scene/Model.js:3810:36)
    at PrimitiveCollection.update (http://localhost:8080/Source/Scene/PrimitiveCollection.js:366:27)
    at updatePrimitives (http://localhost:8080/Source/Scene/Scene.js:2189:27)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2105:9)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:1973:17)
    at render (http://localhost:8080/Source/Scene/Scene.js:2399:9)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:2437:13)
    at CesiumWidget.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:686:25)
```

**Comment by lasalvavida** [comment]
@tfili Updated. Nodes with no collada transforms weren't being written; that is fixed now.

**Comment by tfili** [comment]
It's working now except the transparency on the propellers doesn't work anymore.

image

**Comment by tfili** [comment]
Oh wait. Thats probably because I didn't have libpng installed. Let me check with that.

**Comment by tfili** [comment]
@lasalvavida Thanks

**Pull request merged**
