### PR TITLE
Fixed CesiumMan, monster, and brainsteam

### PR DESCRIPTION
**Pull request by lilleyse**
I made some tweaks to these files in Blender and then re-exported them. I verified that they work in Cesium now.

### CODE REVIEW

**Comment by lilleyse** [comment]
Related to: https://github.com/AnalyticalGraphicsInc/cesium/issues/3244

**Comment by tparisi** [comment]
@lilleyse good work! monster looks right but Brainsteam doesn't. The skinning seems to work but the model itself appears to be missing several parts. Does your mode look like this?
brainsteamscreenshot

**Comment by pjcozzi** [comment]
CC #484.

**Comment by pjcozzi** [comment]
Brainsteam works OK in Cesium.

(Sorry about the resolution).

image

**Comment by tparisi** [comment]
Gotcha - so it's on my end. Will open a new issue and investigate.

**Pull request merged**
