### PR TITLE
Update list of glTF2.0-ready tools.

### LINKED ISSUE #867: Who's working on open-source glTF 2.0 projects?
Please leave a comment on what you are working on so the community can best focus our efforts on rolling out glTF 2.0!

Contributions to all projects are welcome and much appreciated.  Please coordinate with the devs listed below, and we'll keep this issue updated.

# Tools

Project | Devs | Status | Notes
---|---|---|---
[COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF) | @lasalvavida | In progress, https://github.com/KhronosGroup/COLLADA2GLTF/pull/20 | Code review and testing appreciated
[obj2gltf](https://github.com/AnalyticalGraphicsInc/obj2gltf) | @lilleyse | Not started, https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/35 | Contributions encouraged
[gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) | @lasalvavida, @moneimne | In progress, https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/35 |
[glTF Validator](https://github.com/KhronosGroup/glTF-Validator) | @lexaknyazev and @BeardedGnome | In progress |
[batchgltf](https://github.com/feiss/batchgltf) | @feiss | In progress | Batch COLLADA conversion |
[wetzel](https://github.com/AnalyticalGraphicsInc/wetzel) | @HowardWolosky | In progress, https://github.com/AnalyticalGraphicsInc/wetzel/pull/4 |

# Blender

Project | Devs | Status | Notes
---|---|---|---
**Khronos Blender exporter** | | | https://github.com/KhronosGroup/glTF-Blender-Exporter
**Blender exporter** | | | https://github.com/Kupoman/blendergltf
**Blender importer** | @ksons | In progress, https://github.com/ksons/gltf-blender-importer |

# Unity

Project | Devs | Status | Notes
---|---|---|---
**Unity exporter** | @AurL, @PadreZippo, and Microsoft | In progress | (original) https://github.com/tparisi/Unity-glTF-Exporter, (fork) https://github.com/sketchfab/Unity-glTF-Exporter,
[Unity importer](https://github.com/robertlong/UnityGLTFLoader) | @robertlong | In progress | Seeking collaborators 

# Unreal

Project | Devs | Status | Notes
---|---|---|---
**Unreal exporter** | @cedricpinson / Sketchfab | Not started? |

# JavaScript engines

Project | Devs | Status | Notes
---|---|---|---
[three.js](https://threejs.org/) | @takahirox, @donmccurdy | Stable | 
[BabylonJS](http://www.babylonjs.com/) |  @bghgary | Stable, https://github.com/BabylonJS/Babylon.js/tree/master/loaders/src/glTF |
[Cesium](http://cesiumjs.org/) | @lasalvavida | In progress, https://github.com/AnalyticalGraphicsInc/cesium/pull/4808 |
[instant3Dhub / instantUV](http://instant3dhub.org/) | @mlimper | In progress |
[xeogl](http://xeogl.org/) | @xeolabs | In progress |
[PEX](http://vorg.github.io/pex/) | @vorg | In progress |
[grimoirejs-gltf](https://github.com/GrimoireGL/grimoirejs-gltf) | @kyasbal-1994 | In progress, https://github.com/GrimoireGL/grimoirejs-gltf/issues/13 |
[osg.js](https://github.com/cedricpinson/osgjs) | @cedricpinson, @jtorresfabra | In progress |

# C/C++, C#, and Vulkan Loaders

Project | Devs | Status | Notes
---|---|---|---
[tinygltfloader](https://github.com/syoyo/tinygltfloader) (renamed to [tinygltf](https://github.com/syoyo/tinygltf)) | @cedricpinson, @AurL, and Microsoft | In progress, https://github.com/sketchfab/tinygltfloader | https://github.com/syoyo/tinygltfloader/issues/16
[C# Loader](https://github.com/KhronosGroup/glTF-CSharp-Loader) | @BeardedGnome | In progress | https://github.com/KhronosGroup/glTF-CSharp-Loader/pull/1
[VulKan ToolS](https://github.com/McNopper/Vulkan) | @McNopper | In progress | Also Blender -> VKTS -> glTF
[Laugh Engine](github.com/jian-ru/laugh_engine) | @jian-ru | In progress |
[yocto-gl](https://github.com/xelatihy/yocto-gl) | @xelatihy | In progress | Included OBJ to/from glTF
[AssetKit](https://github.com/recp/assetkit) | @recp | In progress | Import/export/render with [libgk](https://github.com/recp/libgk)
[glTF2-loader](https://github.com/Lugdunum3D/glTF2-loader/tree/dev) in [Lugdunum3D](https://github.com/Lugdunum3D/Lugdunum/tree/feature-gltf-integration) | @Sumenia and @saveman71 | In progress |
[gltfpp](https://github.com/mmha/gltfpp) | @mmha | In progress | Plans for WebAssembly

# Rust

Project | Devs | Status | Notes
---|---|---|---
[gltf loader](https://github.com/alteous/gltf) | @alteous | In progress |
[gltf-viewer](https://github.com/bwasty/gltf-viewer) | @bwasty | In progress |

# Ada 2012

Project | Devs | Status | Notes
---|---|---|---
[Orka](https://github.com/onox/orka) | @onox | In progress | OpenGL 4.5 rendering engine

# Samples, docs, and other goodness

Project | Devs | Status | Notes
---|---|---|---
[Sample models](https://github.com/KhronosGroup/glTF-Sample-Models) | @lasalvavida | In progress | Contributions encouraged
[WebGL-PBR](https://github.com/moneimne/WebGL-PBR) | @moneimne | In progress, https://github.com/moneimne/WebGL-PBR/issues/1 | Code review and testing appreciated
[Overview / Reference Card](https://github.com/KhronosGroup/glTF#overview) | @javagl | In progress, #761 |
[Tutorial series](https://github.com/KhronosGroup/glTF-Tutorials/pull/1) | @javagl | Draft | Please review
[PBR tutorial](https://github.com/moneimne/glTF-Tutorials/tree/master/PBR) | @moneimne | Draft | Please review
[gltf-typescript-generator](https://github.com/robertlong/gltf-typescript-generator) | @robertlong | In progress |
[TGen](https://github.com/mlimper/tgen/) | @mlimper | In progress | Simple C++ Tangent Generator
[gltf-vscode](https://github.com/AnalyticalGraphicsInc/gltf-vscode) | @emackey | In progress | https://github.com/KhronosGroup/glTF/issues/867#issuecomment-289024258
[gltf-test 2.0](https://github.com/cx20/gltf-test/tree/2.0) | @cx20 | In progress | How well do engines support glTF 2.0?

---

# TODO

* [ ] @pjcozzi update the main [README.md](https://github.com/KhronosGroup/glTF#gltf-tools) with the tools in this issue.

---

Also, see

* Spec updates, #826
* List of [all glTF Tools](https://github.com/KhronosGroup/glTF#gltf-tools)
* All ways to contribute to glTF, #864 456

### LINKED ISSUE #1030: Indicate glTF2.0-ready tools
A couple formatting ideas, to ensure users can find recommended tools easily. Preferences?

***

> UPDATED: Work-in-progress has been moved out of this comment to a branch. See: https://github.com/KhronosGroup/glTF/compare/donmccurdy-docs-tools-cleanup

### LINKED ISSUE #1037: Microsoft has announced support for glTF in Paint 3D
As per https://blogs.windows.com/windowsexperience/2017/07/12/announcing-more-updates-to-paint-3d-magic-select-enhancements-drawing-tools/#VIIRzsIkuqOuJGB3.97 the [website](https://www.khronos.org/gltf) should be updated to recognize this.

### PR DESCRIPTION
**Pull request by donmccurdy**
**Direct link for review**: https://github.com/KhronosGroup/glTF/tree/donmccurdy-docs-tools-cleanup#quickstart

---

Updates README.md to include glTF2.0-ready tools from #867, and various other threads. Items that only support glTF <=0.8 are removed. The status indicators for each tool are best-guess, based on descriptions and recent activity.

* Fixes #1037.
* Fixes #1030.
* Fixes #867.
* Resolves #801.

### CODE REVIEW

**Comment by saveman71** [comment]
Hi Don,

I'm a maintainer of [Lugdunum3D](https://github.com/Lugdunum3D).

Lugdunum is split in two parts, [the Vulkan 3D engine](https://github.com/Lugdunum3D/Lugdunum), and the [glTF 2.0 loader](https://github.com/Lugdunum3D/glTF2-loader). I'm not sure the engine has a place in this list (although it currently only supports glTF2.0 scenes) but if it does, it should be moved to "C++ and Vulkan" section and the loader should be added to the "C++" section (as it is not Vulkan dependant).

As of right now, the glTF loader is [still incomplete](https://github.com/Lugdunum3D/glTF2-loader/issues/2) but satisfies our current needs in the engine. We'll progressively add new features and improve support of the spec and we'll gladly accept any contribution.

**Comment by donmccurdy** [comment]
Thanks @saveman71  — I've updated the PR accordingly.

**Comment by pjcozzi** [comment]
> COLLADA2GLTF

2.0 is still in progress, it is close...and stalled: https://github.com/KhronosGroup/COLLADA2GLTF/compare/2.0

> Cesium

Will not be 2.0 until the August release.

> WebGL Samples

Maybe call this "WebGL Sample Code."  Samples could mean lots of things like assets.

I wonder if we should also feature a few at the top since there are some very strong implementations kinda of buried in the list.  Could also be a separate PR.

**Comment by kyasbal-1994** [comment]
Hello @donmccurdy ,

I'm contributor of gltf-loader for Grimoire.js.
Currently our latest version of gltf-loader supports only glTF2.0 except any extensions of glTF and specific features listed below.
* Sparse array buffer
* Vertex morph
* lights(placed by model files. Users can use `<light>` of Grimoire.js instead currently)

And several bugs can be observed. (related to texture configurations and interleave array buffers)

(Old version of gltf-loader supports glTF1.0 instead. But, most of the part of the loader was rewritten for supporting glTF2.0. 
Therefore, we plan to reimplement glTF1.0 loader for current loader to be able to load glTF1.0 model also)

However, as far as written in [gltf-test](https://github.com/cx20/gltf-test/tree/2.0) (powered by @cx20, he is also actually contributor of our library) , most of models can be loaded correctly.

I can't determine what should be written in Grimoire.js section of the page(status 2.0 or ?). So, could you correct that?

**Comment by pjcozzi** [comment]
@shrekshao's [minimal-gltf-loader](https://github.com/shrekshao/minimal-gltf-loader) was updated to glTF 2.0.

https://twitter.com/xeographics/status/883356452873809920

**Comment by shrekshao** [comment]
@pjcozzi  .... I think that's just one of my playfield toy.... It's far from being a complete sample demo. I'll let you know when it's ready for an announcement. Thanks for the shout!

**Comment by pjcozzi** [comment]
Perhaps just label it here as "in progress" - it could help you get contributors.

**Comment by donmccurdy** [comment]
Thanks all, I've made these updates to the PR.

@kyasbal-1994 — Thanks for clarifying; I think it's fine to describe it as glTF2.0 with a note about the supported/unsupported features.

**Comment by pjcozzi** [comment]
Looks great!  Let's merge and make any additional tweaks with PRs.

@javagl when ready, could you open a PR to add the overview / reference card here?  I think that was very impactful for 1.0.

**Pull request merged**
