### PR TITLE
Added clarification about regular nodes in a joint hierarchy

### PR DESCRIPTION
**Pull request by Nehon**
As discussed and requested here https://github.com/KhronosGroup/glTF/issues/1108

### CODE REVIEW

**Comment by bghgary** [comment]
FYI: This will have a merge conflict with #1195

**Comment by Nehon** [comment]
mhh are you sure? seems the PR you mention changed the "Skin" section, this one changes the  "Joint Hierarchy" section.
Anyway if there is any conflict I'll rebase.

**Comment by bghgary** [comment]
Ahh, my mistake. Never mind then. 😊

**Comment by pjcozzi** [comment]
@lexaknyazev do you want to look at this?

**Comment by pjcozzi** [comment]
Thanks again @Nehon!

**Pull request merged**
