### PR TITLE
GLB v.2 Specification

### PR DESCRIPTION
**Pull request by lexaknyazev**
From #828.
Before merging, we must give this appendix a number and put a link to it in the main spec.

CC @pjcozzi @sbtron @bghgary @javagl

### CODE REVIEW

**Comment by pjcozzi** [comment]
Looks great, nice job!

For searchability inside the spec, do you think this should be in the main README.md?

**Comment by lexaknyazev** [comment]
> For searchability inside the spec, do you think this should be in the main README.md?

I'd wait until we have all appendices (PBR equations, tangent-space reconstruction for morph targets) and evaluate what's better: one giant file or several interlinked.

**Comment by pjcozzi** [comment]
Sounds good.

**Comment by bghgary** [comment]
Looks good to me.

**Comment by bghgary** [comment]
Is it guaranteed that the JSON chunk is the first chunk in the file?

**Comment by lexaknyazev** [comment]
> Is it guaranteed that the JSON chunk is the first chunk in the file?

Yes. I've added a note, please see if it's sufficient.

**Pull request merged**
