### PR TITLE
Updates syntax for consistency

### PR DESCRIPTION
**Pull request by DigiTec**
This change tries to ensure a consistent syntax across brace styles, comparisons, line breaking and usage of console functions appropriate to the conditions they are flagging.

There are a couple of small functional changes exposed by:
1. Ordering of if statements to remove redundant checks.
2. An if check on uri to make sure it exists before we try to resolve it.
3. Object.keys always returns non-null so removed a null check.

Still unsure how to properly run tests, will investigate that for future pulls. Perhaps even try to set up testing on pull requests?

### CODE REVIEW

**Comment by DigiTec** [comment]
Next set of changes will start functional fixes. I've spotted a few bugs while doing this once over and will be adding fixes for those once I create some local tests that hit the issues.

**Comment by pjcozzi** [comment]
@DigiTec are you finding this dummy loader valuable (seems like yes)?  When I first started with glTF, I started with it, then quickly moved to my own loader.  I _thought_ - perhaps incorrectly - that this dummy loader was not that useful to the community so we were thinking of removing it as we start to separate this repo into a few repos to better organize the spec, COLLADA2GLTF converter, and sample models.

However given your recent contributions here, I'm starting to rethink this.  Should we keep it and continue to maintain it as you have?

**Comment by pjcozzi** [comment]
CC #490

**Comment by pjcozzi** [comment]
@DigiTec any thoughts here?

> @DigiTec are you finding this dummy loader valuable (seems like yes)? When I first started with glTF, I started with it, then quickly moved to my own loader. I thought - perhaps incorrectly - that this dummy loader was not that useful to the community so we were thinking of removing it as we start to separate this repo into a few repos to better organize the spec, COLLADA2GLTF converter, and sample models.
>
> However given your recent contributions here, I'm starting to rethink this. Should we keep it and continue to maintain it as you have?

**Comment by pjcozzi** [comment]
This will most likely be removed.

**Pull request closed without merging**
