### PR TITLE
Fix path to sample models in threejs loader

### PR DESCRIPTION
**Pull request by 5chdn**
It seems someone renamed the sample models. I wasn't able to run the threejs loader at all.

Please excuse the whitespace obfuscation, but the document was really a mess with untrimmed whitespaces and mixed tabs and spaces everywhere. My editor does that automatically.

Here are the changes:

L147: wrong case to threejs OrbitControls.js
L400-498: wrong sampleModel pathes.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @5chdn!  The models were renamed in #579 and we missed this.

@tparisi did you want to review before merging?

**Comment by pjcozzi** [comment]
@tparisi thoughts here?

**Comment by emackey** [comment]
This is obsolete now with #740.

**Comment by pjcozzi** [comment]
Thanks just the same @5chdn!

**Comment by 5chdn** [comment]
:+1:

**Pull request closed without merging**
