### PR TITLE
Web3D SRC Extension

### PR DESCRIPTION
**Pull request by mlimper**
This is a pull request containing the proposed extension WEB3D_SRC.

It depends on EXT_binary_glTF and EXT_quantized_attributes.

This extension mainly provides the possibility to use (binary) glTF assets within other structured 3D scene descriptions, such as X3D or VRML content. As such, it does not introduce _any_ changes to the glTf schema (which is uncommon for an extension). However, it proposes a referencing scheme that allows to refer to binary glTF shape content (`meshes`, `materials`, `textures`) from the outside, and it defines some rules how binary glTF content for shapes  should be treated when just a URL is specified.

That said, it is an open question whether this should really be seen as an extension, since it does not introduce any changes to the core glTF spec.
Instead, this proposal could also become part of the core glTF specification, for example, providing a referencing scheme and building a bridge to the VRML / X3D world.

### CODE REVIEW

**Comment by mlimper** [comment]
Preview:
https://github.com/mlimper/glTF/tree/WEB3D_SRC_Extension/extensions/Vendor/WEB3D_SRC

**Comment by pjcozzi** [comment]
Thanks @mlimper.  I am at a conference today (actually two conferences) and will look at this tomorrow.

> That said, it is an open question whether this should really be seen as an extension, since it does not introduce any changes to the core glTF spec.
Instead, this proposal could also become part of the core glTF specification, for example, providing a referencing scheme and building a bridge to the VRML / X3D world.

Interesting...will think about this.

**Comment by pjcozzi** [comment]
This references glTF lights in a few places.  I suggest removing the references since lights are in an extension now (#84).

**Comment by pjcozzi** [comment]
EXT_binary_glTF should be KHR_binary_glTF.

**Comment by pjcozzi** [comment]
In the **Addressing Scheme for SRC content** section, I think it is worthwhile to explicitly mention that all these types (meshes, materials, and textures - and all top-level glTF objects) share one namespace so, for example, there will never be a mesh and material with the same name.

**Comment by pjcozzi** [comment]
```json
"extensions" : {},
"extras" : {}   
```
Remove these from the example to keep them clean.

**Comment by pjcozzi** [comment]
I suggest that we
* Add a short non-normative section to the glTF 1.0 spec that recommends using `#` when referencing a top-level glTF object (mesh, material, etc.) by its id and the glTF's file, e.g., `model.gltf#material_id`.
* Do not include WEB3D_SRC as an extension.  Instead, the extension - with some wording tweaks - could be a standalone spec for SRC.
* Keep this all in mind when we finish the extension in #37.

CC @tparisi

**Comment by mlimper** [comment]
Thanks for the feedback. I have updated the proposal.

@DrX3D This could be a kind of spec describing the integration of (binary) glTF content into X3D, entitled SRC. Since you have already been working on this topic, let me add you to this conversation.

It will be interesting to figure out together where we finally put the information from this proposal - glTF spec, standalone document hosted / provided together with glTF spec, standalone document somewhere else, ...?

**Comment by brutzman** [comment]
SRC providing common capabilities with binary glTF keeps looking better and better.  Thanks for all of the great efforts on this work.

SRC will not only be critical for the forthcoming X3D Efficient Binary Encoding (EBE) but we expect that it will help all X3D file encodings and language APIs.  Such shape interoperability with binary glTF can become a critical new capability that hopefully can be maximized for use by all Web authors.

http://www.web3d.org/specifications
http://www.web3d.org/specifications/X3dSpecificationRelationships.png
http://www.web3d.org/specifications/X3dSpecificationRelationships.pdf

**Comment by mlimper** [comment]
Maybe the content proposed within this pull request would better fit into some document on the "X3D side" of this connection, it could then also contain the relationship diagram, for example.

The file extension will then probably be ".glb", the regular binary glTF extension... a mimetype should also be on the way, at least it is planned, I think.

@pjcozzi What do you think?

**Comment by pjcozzi** [comment]
@mlimper I agree.

I added the following to the glTF spec:

> It is recommended that container formats reference a glTF object by ID by concatenating the asset's path, `#`, and the ID, e.g., `asset.gltf#material_id`.

a09353f43ab99f062830a3c0553a38b88619941b

**Comment by mlimper** [comment]
Thanks - looks fine!

**Pull request closed without merging**
