### PR TITLE
Clarify the morph displacements order

### PR DESCRIPTION
**Pull request by lexaknyazev**
Fixes https://github.com/KhronosGroup/glTF/issues/1646.

### CODE REVIEW

**Comment by emackey** [comment]
Can we make an explicit reference to skinning here?  I had to re-read #1646 and read "any transformation matrices affecting the mesh vertices" about 3 times before I started to take that as meaning that morphs happen before skinning (as opposed to node transforms).  Perhaps I'm being dense, but could we spell it out for folks?

**Comment by lexaknyazev** [comment]
Given that skinning is effectively defined as applying per-vertex transformation matrices (rather than per-mesh), I thought that "any" covers both cases. Spelling that out won't hurt though.

**Review by javagl — APPROVED** [review]
It's good to have that explicit.

(And I didn't have that on the radar. I'll try to have a look at existing implementations. A sample model for dedicatedly testing this could be nice...)

**Comment by emackey** [comment]
> A sample model for dedicatedly testing this could be nice...

I never did submit my balloon test model... It looks a little wonky, but it uses morphing to inflate / deflate, and uses skinning to "flop over" when deflated.  It demonstrates well why this order is correct; I'll have to build a readme for it and post it someday.

**Review by emackey — APPROVED** [review]

**Pull request merged**
