### PR TITLE
Fixed ordering of blendFuncSeparate

### PR DESCRIPTION
**Pull request by lilleyse**
The ordering was incorrect in this area. Uncovered through this post on the Cesium forum: https://groups.google.com/forum/#!msg/cesium-dev/BP_fs8K19ww/n2SBwzEsBAAJ

### CODE REVIEW

**Comment by pjcozzi** [comment]
Very nice catch,

Please update the schema as well: https://github.com/KhronosGroup/glTF/blob/master/specification/schema/technique.states.functions.schema.json#L44

Looks like the example is OK: https://github.com/KhronosGroup/glTF/blob/master/specification/schema/examples/techniques.json

Did you also spot check the models in the `sampleModels` directory?

**Comment by lexaknyazev** [comment]
Related: https://github.com/KhronosGroup/glTF/pull/585

**Comment by lilleyse** [comment]
@pjcozzi Thanks for noticing those other areas. My update fixes the remaining issues. The sample models are all fine.

**Comment by pjcozzi** [comment]
Thanks @lilleyse!

This and #585 were my bad for sure.  Good catch!

**Pull request merged**
